{{- if .Values.dockerSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerSecret.name }}
  namespace: {{ include "python-app.namespace" . }}
# This type tells Kubernetes this is a Docker registry credential
type: kubernetes.io/dockerconfigjson
# stringData lets us write JSON directly (Kubernetes base64-encodes it internally)
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "{{ .Values.dockerSecret.auth }}"
        }
      }
    }
{{- end}}