{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "python-app.namespace" . }}
  labels:
    # Labels help identify and select resources
    {{- include "python-app.labels" . | nindent 4 }}
    name: {{ include "python-app.namespace" . }}
{{- end }}